from __future__ import annotations

import argparse
import json
import re
import unicodedata
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DEFAULT_OUTPUT = DATA / "pyojun_words.txt"

HANGUL_RE = re.compile(r"^[\uac00-\ud7a3]+$")
WORD_UNIT = "\ub2e8\uc5b4"
SKIPPED_POS = {"\uc5b4\ubbf8", "\uc870\uc0ac", "\uc811\uc0ac"}


def normalize_headword(value: Any) -> str:
    raw = unicodedata.normalize("NFC", str(value or "").strip().lstrip("\ufeff"))
    if not raw or raw.startswith("-") or raw.endswith("-"):
        return ""

    word = re.sub(r"[\s\-^0-9]", "", raw)
    return word if len(word) >= 2 and HANGUL_RE.fullmatch(word) else ""


def as_dicts(value: Any) -> Iterable[dict[str, Any]]:
    if isinstance(value, dict):
        yield value
        return
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                yield item


def iter_items(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig") as file:
        data = json.load(file)
    channel = data.get("channel") if isinstance(data, dict) else None
    items = channel.get("item") if isinstance(channel, dict) else None
    yield from as_dicts(items)


def extract_words(source_dir: Path) -> tuple[list[str], Counter[str], Counter[str]]:
    words: set[str] = set()
    skipped = Counter()
    accepted_pos = Counter()

    for path in sorted(source_dir.glob("*.json")):
        for item in iter_items(path):
            word_info = item.get("word_info") if isinstance(item, dict) else None
            if not isinstance(word_info, dict):
                skipped["missing_word_info"] += 1
                continue
            if word_info.get("word_unit") != WORD_UNIT:
                skipped["non_word_unit"] += 1
                continue

            pos_values = {str(pos.get("pos") or "") for pos in as_dicts(word_info.get("pos_info"))}
            if pos_values & SKIPPED_POS:
                skipped["skipped_pos"] += 1
                continue

            word = normalize_headword(word_info.get("word"))
            if not word:
                skipped["non_hangul_headword"] += 1
                continue

            words.add(word)
            for pos in pos_values or {"unknown"}:
                accepted_pos[pos or "unknown"] += 1

    return sorted(words), skipped, accepted_pos


def write_words(words: list[str], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(
            [
                "# Extracted from the Standard Korean Dictionary full JSON download.",
                "# Generated by tools/extract_pyojun_words.py.",
                *words,
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not args.source_dir.exists():
        raise SystemExit(f"source directory not found: {args.source_dir}")

    words, skipped, accepted_pos = extract_words(args.source_dir)
    write_words(words, args.output)

    print(f"wrote {args.output}")
    print(f"words={len(words)}")
    print("skipped=" + ", ".join(f"{key}:{value}" for key, value in skipped.most_common()))
    print("pos=" + ", ".join(f"{key}:{value}" for key, value in accepted_pos.most_common()))


if __name__ == "__main__":
    main()
