from __future__ import annotations

import argparse
import json
import re
import unicodedata
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DEFAULT_OUTPUT = DATA / "woorimalsam_words.txt"

HANGUL_RE = re.compile(r"^[가-힣]+$")
SKIPPED_POS = {"어미", "조사", "접사"}


def normalize_headword(value: Any) -> str:
    raw = unicodedata.normalize("NFC", str(value or "").strip().lstrip("\ufeff"))
    if not raw or raw.startswith("-") or raw.endswith("-"):
        return ""
    if any(char.isspace() for char in raw):
        return ""

    word = raw.replace("^", "").replace("-", "")
    return word if HANGUL_RE.fullmatch(word) else ""


def as_dicts(value: Any) -> Iterable[dict[str, Any]]:
    if isinstance(value, dict):
        yield value
        return
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                yield item


def iter_items(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig") as file:
        data = json.load(file)
    channel = data.get("channel") if isinstance(data, dict) else None
    items = channel.get("item") if isinstance(channel, dict) else None
    yield from as_dicts(items)


def extract_words(source_dir: Path) -> tuple[list[str], Counter[str], Counter[str]]:
    words: set[str] = set()
    skipped = Counter()
    accepted_types = Counter()

    for path in sorted(source_dir.glob("*.json")):
        for item in iter_items(path):
            wordinfo = item.get("wordinfo") if isinstance(item, dict) else None
            if not isinstance(wordinfo, dict):
                skipped["missing_wordinfo"] += 1
                continue
            if wordinfo.get("word_unit") != "어휘":
                skipped["non_word_unit"] += 1
                continue

            senses = list(as_dicts(item.get("senseinfo")))
            pos_values = {str(sense.get("pos") or "") for sense in senses}
            if pos_values & SKIPPED_POS:
                skipped["skipped_pos"] += 1
                continue

            word = normalize_headword(wordinfo.get("word"))
            if not word:
                skipped["non_hangul_headword"] += 1
                continue

            words.add(word)
            for sense in senses:
                accepted_types[str(sense.get("type") or "unknown")] += 1

    return sorted(words), skipped, accepted_types


def write_words(words: list[str], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(
            [
                "# Extracted from the Woori Mal Sam full JSON download.",
                "# Generated by tools/extract_woorimalsam_words.py.",
                *words,
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not args.source_dir.exists():
        raise SystemExit(f"source directory not found: {args.source_dir}")

    words, skipped, accepted_types = extract_words(args.source_dir)
    write_words(words, args.output)

    print(f"wrote {args.output}")
    print(f"words={len(words)}")
    print("skipped=" + ", ".join(f"{key}:{value}" for key, value in skipped.most_common()))
    print("types=" + ", ".join(f"{key}:{value}" for key, value in accepted_types.most_common()))


if __name__ == "__main__":
    main()
