from __future__ import annotations

import argparse
import json
import os
import re
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from collections import deque
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
DEFAULT_OUTPUT = DATA / "stdict_api_words.txt"
DEFAULT_STATE = DATA / "stdict_api_fetch_state.json"
DEFAULT_ENDPOINT = "https://stdict.korean.go.kr/api/search.do"
API_KEY_ENV = "STDICT_API_KEY"

HANGUL_BASE = 0xAC00
HANGUL_END = 0xD7A3
HANGUL_RE = re.compile(r"^[\uac00-\ud7a3]+$")
SKIPPED_POS = {"\uc5b4\ubbf8", "\uc870\uc0ac", "\uc811\uc0ac"}


class ApiError(RuntimeError):
    pass


def normalize_headword(value: Any) -> str:
    raw = unicodedata.normalize("NFC", str(value or "").strip().lstrip("\ufeff"))
    if not raw or raw.startswith("-") or raw.endswith("-"):
        return ""

    word = re.sub(r"[\s\-^0-9]", "", raw)
    return word if len(word) >= 2 and HANGUL_RE.fullmatch(word) else ""


def iter_hangul_syllables() -> list[str]:
    return [chr(code) for code in range(HANGUL_BASE, HANGUL_END + 1)]


def as_dicts(value: Any) -> Iterable[dict[str, Any]]:
    if isinstance(value, dict):
        yield value
        return
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                yield item


def read_words(path: Path) -> set[str]:
    if not path.exists():
        return set()

    words: set[str] = set()
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        word = normalize_headword(line)
        if word:
            words.add(word)
    return words


def write_words(path: Path, words: set[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "# Fetched from the Standard Korean Dictionary Open API.",
                "# Generated by tools/fetch_stdict_api_words.py.",
                *sorted(words),
                "",
            ]
        ),
        encoding="utf-8",
    )


def load_state(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SystemExit(f"state file is not valid JSON: {path}: {error}") from error


def save_state(
    path: Path,
    pending: deque[str],
    truncated_prefixes: list[str],
    request_count: int,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "pending_prefixes": list(pending),
        "truncated_prefixes": truncated_prefixes,
        "request_count": request_count,
        "updated_at": int(time.time()),
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def request_json(params: dict[str, str], args: argparse.Namespace) -> dict[str, Any]:
    query = urllib.parse.urlencode(params)
    url = f"{args.endpoint}?{query}"
    request = urllib.request.Request(url, headers={"Accept": "application/json", "User-Agent": args.user_agent})

    last_error: Exception | None = None
    for attempt in range(args.retries + 1):
        if args.delay > 0:
            time.sleep(args.delay)
        try:
            with urllib.request.urlopen(request, timeout=args.timeout) as response:
                payload = response.read().decode("utf-8-sig")
            data = json.loads(payload)
            if isinstance(data, dict) and "error" in data:
                error = data.get("error") or {}
                code = error.get("error_code", error.get("code", "unknown"))
                message = error.get("message", "unknown API error")
                raise ApiError(f"API error {code}: {message}")
            if not isinstance(data, dict):
                raise ApiError("API response was not an object")
            return data
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError, ApiError) as error:
            last_error = error
            if attempt >= args.retries:
                break
            time.sleep(args.retry_delay * (attempt + 1))

    raise ApiError(str(last_error))


def fetch_page(prefix: str, method: str, start: int, args: argparse.Namespace) -> tuple[int, list[dict[str, Any]]]:
    params = {
        "key": args.key,
        "q": prefix,
        "req_type": "json",
        "advanced": "y",
        "target": "1",
        "method": method,
        "type1": "word",
        "start": str(start),
        "num": str(args.page_size),
    }
    data = request_json(params, args)
    channel = data.get("channel") if isinstance(data, dict) else None
    if not isinstance(channel, dict):
        raise ApiError("API response is missing channel")
    total = parse_int(channel.get("total"))
    return total, list(as_dicts(channel.get("item")))


def parse_int(value: Any) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def words_from_items(items: Iterable[dict[str, Any]]) -> set[str]:
    words: set[str] = set()
    for item in items:
        pos = str(item.get("pos") or "")
        if pos in SKIPPED_POS:
            continue
        word = normalize_headword(item.get("word"))
        if word:
            words.add(word)
    return words


def fetch_exact_word(prefix: str, args: argparse.Namespace) -> tuple[set[str], int]:
    total, items = fetch_page(prefix, "exact", 1, args)
    request_count = 1
    words = {word for word in words_from_items(items) if word == prefix}
    for start in range(1 + args.page_size, min(total, args.max_start) + 1, args.page_size):
        _, page_items = fetch_page(prefix, "exact", start, args)
        request_count += 1
        words.update(word for word in words_from_items(page_items) if word == prefix)
    return words, request_count


def fetch_prefix(prefix: str, alphabet: list[str], args: argparse.Namespace) -> tuple[set[str], list[str], bool, int]:
    total, first_items = fetch_page(prefix, "start", 1, args)
    request_count = 1
    if total == 0:
        return set(), [], False, request_count

    if total > args.max_start:
        words: set[str] = set()
        if len(prefix) >= 2:
            exact_words, exact_requests = fetch_exact_word(prefix, args)
            words.update(exact_words)
            request_count += exact_requests

        if len(prefix) >= args.max_prefix_length:
            words.update(words_from_items(first_items))
            for start in range(1 + args.page_size, args.max_start + 1, args.page_size):
                _, page_items = fetch_page(prefix, "start", start, args)
                request_count += 1
                words.update(words_from_items(page_items))
            return words, [], True, request_count

        children = [prefix + syllable for syllable in alphabet]
        return words, children, False, request_count

    words = words_from_items(first_items)
    for start in range(1 + args.page_size, total + 1, args.page_size):
        _, page_items = fetch_page(prefix, "start", start, args)
        request_count += 1
        words.update(words_from_items(page_items))
    return words, [], False, request_count


def read_prefixes(path: Path) -> list[str]:
    prefixes: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        value = unicodedata.normalize("NFC", line.strip().lstrip("\ufeff"))
        if value and not value.startswith("#") and HANGUL_RE.fullmatch(value):
            prefixes.append(value)
    return prefixes


def initial_prefixes(args: argparse.Namespace) -> list[str]:
    prefixes: list[str] = []
    if args.prefix_file:
        prefixes.extend(read_prefixes(args.prefix_file))
    prefixes.extend(args.prefix or [])
    if not prefixes:
        prefixes = iter_hangul_syllables()
    return unique(prefixes)


def unique(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch Standard Korean Dictionary headwords through the official search API."
    )
    parser.add_argument("--key", default=os.environ.get(API_KEY_ENV, ""), help=f"API key. Defaults to ${API_KEY_ENV}.")
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE)
    parser.add_argument("--restart", action="store_true", help="Ignore an existing state file and start over.")
    parser.add_argument("--prefix", action="append", help="Fetch only this Hangul prefix. Can be repeated.")
    parser.add_argument("--prefix-file", type=Path, help="UTF-8 file containing one Hangul prefix per line.")
    parser.add_argument("--page-size", type=int, default=100)
    parser.add_argument("--max-start", type=int, default=1000)
    parser.add_argument("--max-prefix-length", type=int, default=6)
    parser.add_argument("--delay", type=float, default=0.2, help="Delay before each API request, in seconds.")
    parser.add_argument("--timeout", type=float, default=20)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--retry-delay", type=float, default=2.0)
    parser.add_argument("--save-every", type=int, default=25, help="Save output and state every N processed prefixes.")
    parser.add_argument("--max-requests", type=int, default=0, help="Stop after this many API requests. 0 means no cap.")
    parser.add_argument("--user-agent", default="kkung-st-dict-fetcher/1.0")
    args = parser.parse_args()

    args.key = str(args.key or "").strip()
    if not args.key:
        raise SystemExit(f"missing API key: set {API_KEY_ENV} or pass --key")
    args.page_size = max(10, min(100, int(args.page_size)))
    args.max_start = max(args.page_size, min(1000, int(args.max_start)))
    args.max_prefix_length = max(1, int(args.max_prefix_length))
    args.save_every = max(1, int(args.save_every))
    return args


def main() -> None:
    args = parse_args()
    alphabet = iter_hangul_syllables()
    words = read_words(args.output)
    truncated_prefixes: list[str] = []
    request_count = 0

    if args.state.exists() and not args.restart:
        state = load_state(args.state)
        pending = deque(str(prefix) for prefix in state.get("pending_prefixes", []) if HANGUL_RE.fullmatch(str(prefix)))
        truncated_prefixes = [str(prefix) for prefix in state.get("truncated_prefixes", [])]
        request_count = parse_int(state.get("request_count"))
        if not pending:
            pending = deque(initial_prefixes(args))
    else:
        pending = deque(initial_prefixes(args))

    queued = set(pending)
    processed = 0
    print(f"loaded words={len(words)} pending={len(pending)} requests={request_count}")

    try:
        while pending:
            prefix = pending.popleft()
            queued.discard(prefix)
            fetched, children, truncated, requests = fetch_prefix(prefix, alphabet, args)
            request_count += requests
            old_count = len(words)
            words.update(fetched)
            processed += 1

            for child in children:
                if child not in queued:
                    queued.add(child)
                    pending.append(child)
            if truncated:
                truncated_prefixes.append(prefix)

            if processed % args.save_every == 0:
                write_words(args.output, words)
                save_state(args.state, pending, truncated_prefixes, request_count)

            print(
                f"prefix={prefix} added={len(words) - old_count} "
                f"children={len(children)} pending={len(pending)} words={len(words)} requests={request_count}"
            )
            if args.max_requests and request_count >= args.max_requests:
                print("stopping because --max-requests was reached")
                break
    finally:
        write_words(args.output, words)
        save_state(args.state, pending, truncated_prefixes, request_count)

    print(f"wrote {args.output}")
    print(f"words={len(words)} requests={request_count} pending={len(pending)}")
    if truncated_prefixes:
        print("truncated_prefixes=" + ", ".join(truncated_prefixes[:20]))


if __name__ == "__main__":
    main()
